function allEvents = loadEvents(path)
    % Load control data from TCT auto-generated files (.ADS).
    % Read the file ALLEVENTS.ADS containing all the possible events and
    % outputs a column array with all the events, one per line.
    % This is a autogenerated file.
    fid = fopen(path);
    lines = textscan(fid, "%s", "Delimiter","\n");

    % Data of the events always begins at line 28.
    beginingOfdata = 28;
    allEvents = zeros(numel(lines{1}) - beginingOfdata,1);
    j = 1;
    for i = 28:numel(lines{1})
        % take off trailing spaces and substitute the blank string by empty
        % spaces.
        line = char(strrep(strtrim(lines{1}{i})," ", ""));
        event = str2double(line(2:end-1));
        
        if isnan(event)
            break
        end
        allEvents(j) = event;
        j = j + 1;
    end    
    fclose(fid);
end

